spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tribles/spring-cloud-config-server-repo.git
server:
  port: 8888
management:
  security:
    enabled: false